id: detailed-land-cover-classification
docker:
    host: unix:///var/run/docker.sock
    image: wacodis.eo.imagelearn:latest
    container: wacodis-eo-imagelearn
    workDir: /public
command:
    folder: python
    name: /cli/workflow.py
    arguments:
        - name: -input
          type: wps-process-reference
          value: OPTICAL_IMAGES_SOURCES
          quantity: multiple
        - name: -training
          type: wps-process-reference
          value: REFERENCE_DATA
          quantity: single
        - name: -watermask
          type: wps-process-reference
          value: ATKIS_WATER_DATA
          quantity: single
        - name: -industry
          type: wps-process-reference
          value: ATKIS_INDUSTRY_DATA
          quantity: single
        - name: -elevation
          type: wps-process-reference
          value: ELEVATION_DATA
          quantity: single
        - name: -result
          type: wps-process-reference
          value: RESULT_PATH
          quantity: single
        - name: -epsg
          type: static-option
          value: 32632
          quantity: single
